/**
 * GitHub Pull Request operations.
 * Mirrors Go internal/github/pr.go behaviour.
 */

import { readFile, writeFile, realpath } from 'node:fs/promises';
import { resolve, join, sep } from 'node:path';
import type { GitHubClient } from './client.js';
import { REPO_URL } from '../config/types.js';
import { logger } from '../utils/logger.js';
import { redact } from '../redaction/redactor.js';

// ---------------------------------------------------------------------------
// Types
// ---------------------------------------------------------------------------

export interface PRRecommendation {
  resource_id: string;
  title: string;
  description: string;
  current_config: string;
  recommended_config: string;
  estimated_savings: number;
  confidence: number;
  risk?: string;
  /** Security rule ID (e.g. "SG-SEC-001"). Used in the security PR findings table. */
  ruleId?: string;
  /** Finding severity for security PRs ("critical" | "high" | "medium" | "low"). */
  severity?: string;
}

export interface PROptions {
  title?: string;
  body?: string;
  head: string;
  base?: string;
  draft?: boolean;
  labels?: string[];
  reviewers?: string[];
}

export interface PR {
  number: number;
  html_url: string;
  title: string;
  state: string;
  draft: boolean;
  created_at: string;
}

/** Minimal structure for korinfra-manifest.json */
export type korinfraManifest = Record<string, unknown>;

// ---------------------------------------------------------------------------
// PR body builder
// ---------------------------------------------------------------------------

/**
 * Builds the standard korinfra PR body from recommendation data.
 * Mirrors Go BuildPRBody in internal/github/pr.go.
 */
export function buildPRBody(
  recommendations: PRRecommendation[],
  totalSavings: number,
  currency?: string,
): string {
  const sym = (!currency || currency === 'USD') ? '$' : `${currency} `;
  const isSecurity = recommendations.some(r => r.ruleId ?? r.severity) ||
    (totalSavings === 0 && recommendations.length > 0 && recommendations.every(r => r.estimated_savings === 0));
  const lines: string[] = [];

  const heading = isSecurity ? '## korinfra Security Fix' : '## korinfra Cost Optimization';
  lines.push(`${heading}\n`);
  lines.push(
    `> Generated by [korinfra](${REPO_URL}) — Smart infrastructure. Lower costs. One command at a time.\n`,
  );

  const esc = (s: string) => s
    .replace(/\\/g, '\\\\')
    .replace(/[\r\n]+/g, ' ')
    .replace(/\|/g, '\\|')
    .replace(/`/g, "'")
    .replace(/[[\]!*_~]/g, (ch) => `\\${ch}`);

  if (isSecurity) {
    const SEVERITY_ORDER = ['critical', 'high', 'medium', 'low'];
    const resourceNames = [...new Set(recommendations.map(r => `\`${esc(r.resource_id)}\``))].join(', ');
    lines.push(`This PR applies ${recommendations.length} security ${recommendations.length === 1 ? 'fix' : 'fixes'} to ${resourceNames}, detected by korinfra static analysis.\n`);

    // Group by severity
    const bySeverity = new Map<string, PRRecommendation[]>();
    for (const rec of recommendations) {
      const sev = rec.severity ?? 'medium';
      const bucket = bySeverity.get(sev) ?? [];
      bucket.push(rec);
      bySeverity.set(sev, bucket);
    }

    const SEV_EMOJI: Record<string, string> = { critical: '🔴', high: '🟠', medium: '🟡', low: '🟢' };
    lines.push('### Security Findings Fixed\n');
    for (const sev of SEVERITY_ORDER) {
      const group = bySeverity.get(sev);
      if (!group || group.length === 0) continue;
      const emoji = SEV_EMOJI[sev] ?? '';
      lines.push(`#### ${emoji} ${sev.charAt(0).toUpperCase() + sev.slice(1)} (${group.length})\n`);
      lines.push('| Rule | Resource | Issue | Fix Applied |');
      lines.push('|------|----------|-------|-------------|');
      for (const rec of group) {
        const ruleId = esc(rec.ruleId ?? rec.title.split(' ')[0] ?? '—');
        lines.push(`| \`${ruleId}\` | \`${esc(rec.resource_id)}\` | ${esc(rec.description)} | ${esc(rec.recommended_config)} |`);
      }
      lines.push('');
    }

    lines.push('### What Changed\n');
    recommendations.forEach((rec, i) => {
      const confidence = (rec.confidence * 100).toFixed(0);
      const ruleTag = rec.ruleId ? ` \`${esc(rec.ruleId)}\`` : '';
      lines.push(`**${i + 1}. ${esc(rec.title)}**${ruleTag}`);
      lines.push(`- **Resource:** \`${esc(rec.resource_id)}\``);
      lines.push(`- **Why it matters:** ${esc(rec.description)}`);
      if (rec.current_config) {
        lines.push(`- **Before:** \`${esc(rec.current_config)}\``);
      }
      lines.push(`- **After:** \`${esc(rec.recommended_config)}\``);
      lines.push(`- **Confidence:** ${confidence}%${rec.risk ? ` · **Risk:** ${esc(rec.risk)}` : ''}`);
      lines.push('');
    });
  } else {
    lines.push('### Cost Impact\n');
    lines.push(
      '| Resource | Current Config | Recommended | Est. Savings/mo | Confidence |',
    );
    lines.push(
      '|----------|---------------|-------------|-----------------|------------|',
    );
    for (const rec of recommendations) {
      const savings = rec.estimated_savings.toFixed(2);
      const confidence = (rec.confidence * 100).toFixed(0);
      const safeResourceId = esc(rec.resource_id).replace(/`/g, "'");
      lines.push(
        `| \`${safeResourceId}\` | ${esc(rec.current_config)} | ${esc(rec.recommended_config)} | ${sym}${savings} | ${confidence}% |`,
      );
    }
    lines.push('');
    lines.push(`**Total estimated savings: ${sym}${totalSavings.toFixed(2)}/month**\n`);

    lines.push('### Recommendations\n');
    recommendations.forEach((rec, i) => {
      lines.push(`${i + 1}. **${esc(rec.title)}** — ${esc(rec.description)}`);
      if (rec.risk) {
        lines.push(`   - Risk: ${esc(rec.risk)}`);
      }
    });
  }

  lines.push('');
  lines.push('### How to Review\n');
  if (isSecurity) {
    lines.push('- [ ] Review Terraform changes — confirm fix is correct and minimal');
    lines.push('- [ ] Run `terraform plan` to preview AWS changes');
    lines.push('- [ ] Test in a non-production environment first');
    lines.push('- [ ] Apply with `terraform apply` after approval');
    lines.push('- [ ] Re-run `korinfra security` to confirm finding is resolved\n');
  } else {
    lines.push('- [ ] Review each changed file — confirm recommendation is appropriate');
    lines.push('- [ ] Test in a non-production environment first');
    lines.push('- [ ] Run `terraform plan` then `terraform apply`\n');
  }

  const now = new Date();
  const ts = now.toISOString().replace('T', ' ').slice(0, 16) + ' UTC';
  lines.push(`---\n*Generated by [korinfra](${REPO_URL}) at ${ts} · [Docs](${REPO_URL}#readme)*`);

  return lines.join('\n');
}

// ---------------------------------------------------------------------------
// Label helpers
// ---------------------------------------------------------------------------

const LABEL_COLORS: Record<string, string> = {
  korinfra: '0075ca',
  'cost-optimization': 'e4e669',
  terraform: '7057ff',
};

function labelColor(label: string): string {
  return LABEL_COLORS[label] ?? 'ededed';
}

// ---------------------------------------------------------------------------
// PR operations
// ---------------------------------------------------------------------------

/**
 * Creates a pull request and optionally adds labels and reviewers.
 */
export async function createPR(
  client: GitHubClient,
  owner: string,
  repo: string,
  opts: PROptions,
): Promise<PR> {
  const base = opts.base ?? 'main';
  const title = opts.title ?? 'korinfra: Cost Optimization Changes';

  const payload = {
    title,
    body: opts.body ?? '',
    head: opts.head,
    base,
    draft: opts.draft ?? false,
  };

  const pr = await client.post<PR>(
    `/repos/${owner}/${repo}/pulls`,
    payload,
  );

  if (!pr) {
    throw new Error('GitHub returned empty response when creating PR');
  }

  if (typeof pr.number !== 'number') {
    throw new Error('Unexpected GitHub API response shape: missing pr.number');
  }

  // Labels — best-effort, non-fatal
  if (opts.labels && opts.labels.length > 0) {
    try {
      await addLabels(client, owner, repo, pr.number, opts.labels);
    } catch (err: unknown) {
      logger.warn(
        { err: { message: redact(err instanceof Error ? err.message : String(err), 'moderate'), status: (err as { status?: number }).status } },
        'Failed to add labels to PR (non-fatal)'
      );
    }
  }

  // Reviewers — best-effort, non-fatal
  if (opts.reviewers && opts.reviewers.length > 0) {
    try {
      await requestReviewers(client, owner, repo, pr.number, opts.reviewers);
    } catch (err: unknown) {
      logger.warn(
        { err: { message: redact(err instanceof Error ? err.message : String(err), 'moderate'), status: (err as { status?: number }).status } },
        'Failed to add reviewers to PR (non-fatal)'
      );
    }
  }

  return pr;
}

/**
 * Adds labels to a PR, creating them on the repo first if missing.
 */
export async function addLabels(
  client: GitHubClient,
  owner: string,
  repo: string,
  prNumber: number,
  labels: string[],
): Promise<void> {
  // Ensure labels exist — ignore errors (422 = already exists)
  await Promise.allSettled(
    labels.map((label) =>
      client.post(`/repos/${owner}/${repo}/labels`, {
        name: label,
        color: labelColor(label),
      }),
    ),
  );

  await client.post(`/repos/${owner}/${repo}/issues/${prNumber}/labels`, {
    labels,
  });
}

/**
 * Requests reviewers on an open pull request.
 */
export async function requestReviewers(
  client: GitHubClient,
  owner: string,
  repo: string,
  prNumber: number,
  reviewers: string[],
): Promise<void> {
  await client.post(
    `/repos/${owner}/${repo}/pulls/${prNumber}/requested_reviewers`,
    { reviewers },
  );
}

// ---------------------------------------------------------------------------
// Manifest helpers (used by `fix pr` subcommand)
// ---------------------------------------------------------------------------

async function validateManifestPath(filePath: string): Promise<void> {
  let realPath: string;
  try {
    realPath = await realpath(filePath);
  } catch {
    // File doesn't exist yet or is unreachable; validate the resolved path
    realPath = resolve(filePath);
  }
  const allowedDir = join(process.cwd(), '.korinfra');
  const normalizedAllowed = allowedDir.endsWith(sep) ? allowedDir : allowedDir + sep;
  if (!realPath.startsWith(normalizedAllowed) && realPath !== allowedDir) {
    throw new Error('Manifest path must be inside .korinfra/ directory');
  }
}

/**
 * Reads korinfra-manifest.json from disk.
 */
export async function readManifest(path: string): Promise<korinfraManifest> {
  await validateManifestPath(path);
  const raw = await readFile(path, 'utf8');
  try {
    return JSON.parse(raw) as korinfraManifest;
  } catch (err) {
    throw new Error(`Failed to parse manifest at ${path}: ${err instanceof Error ? err.message : String(err)}`, { cause: err });
  }
}

/**
 * Writes korinfra-manifest.json to disk.
 */
export async function writeManifest(
  path: string,
  data: korinfraManifest,
): Promise<void> {
  await validateManifestPath(path);
  const writeOpts = process.platform !== 'win32'
    ? { encoding: 'utf8' as const, mode: 0o600 }
    : 'utf8';
  await writeFile(path, JSON.stringify(data, null, 2) + '\n', writeOpts);
}
