/**
 * Tests for src/github/pr.ts — pure functions only (no real API calls).
 */

import { describe, it, expect, beforeEach, afterEach } from 'vitest';
import { writeFile } from 'node:fs/promises';
import { mkdirSync, rmSync } from 'node:fs';
import { join } from 'node:path';
import { randomUUID } from 'node:crypto';
import { buildPRBody, readManifest } from '../../../src/github/pr.js';
import type { PRRecommendation } from '../../../src/github/pr.js';

const ec2Rec: PRRecommendation = {
  resource_id: 'i-0a1b2c3d4e5f67890',
  title: 'Rightsize EC2 instance i-0a1b2c3d4e5f67890',
  description: 'Instance is running at <5% CPU for 14 days. Downsize from m5.2xlarge to m5.xlarge.',
  current_config: 'm5.2xlarge (8 vCPU, 32 GB)',
  recommended_config: 'm5.xlarge (4 vCPU, 16 GB)',
  estimated_savings: 146.00,
  confidence: 0.91,
  risk: 'low',
};

const rdsRec: PRRecommendation = {
  resource_id: 'db-prod-mysql-01',
  title: 'Purchase RDS Reserved Instance for db-prod-mysql-01',
  description: 'RDS instance has been running on-demand for 45 days. RI purchase saves 40%.',
  current_config: 'On-Demand db.r5.2xlarge',
  recommended_config: '1-year RI db.r5.2xlarge',
  estimated_savings: 280.50,
  confidence: 0.87,
};

const ebsRec: PRRecommendation = {
  resource_id: 'vol-0deadbeef1234567',
  title: 'Delete unused EBS volumes',
  description: 'Three EBS volumes are unattached and accruing charges.',
  current_config: 'gp2, 500 GB, unattached | gp2, 200 GB | gp2, 100 GB',
  recommended_config: 'Delete all three volumes',
  estimated_savings: 64.00,
  confidence: 0.98,
  risk: 'low',
};

const allRecs = [ec2Rec, rdsRec, ebsRec];

// ---------------------------------------------------------------------------
// buildPRBody
// ---------------------------------------------------------------------------

describe('buildPRBody — structure and content', () => {
  it('includes header, total savings, markdown table, how-to-review, timestamp, and repo URL', () => {
    const body = buildPRBody(allRecs, 490.50);
    expect(body).toContain('## korinfra Cost Optimization');
    expect(body).toContain('**Total estimated savings: $490.50/month**');
    expect(body).toContain('| Resource | Current Config | Recommended | Est. Savings/mo | Confidence |');
    expect(body).toContain('|----------|');
    expect(body).toContain('### How to Review');
    expect(body).toContain('terraform plan');
    expect(body).toMatch(/Generated by \[korinfra\]\(.*\) at \d{4}-\d{2}-\d{2} \d{2}:\d{2} UTC/);
    expect(body).toContain('https://github.com/korinfra/korinfra');
    expect(buildPRBody(allRecs, 2450)).toContain('$2450.00/month');
  });

  it('renders table rows with resource IDs, confidence percentages, savings, and pipe escaping', () => {
    const body = buildPRBody(allRecs, 490.50);
    expect(body).toContain('`i-0a1b2c3d4e5f67890`');
    expect(body).toContain('`db-prod-mysql-01`');
    expect(body).toContain('`vol-0deadbeef1234567`');
    expect(body).toContain('91%');
    expect(body).toContain('87%');
    expect(body).toContain('98%');
    expect(body).toContain('$146.00');
    expect(body).toContain('$280.50');
    expect(body).toContain('$64.00');
    expect(body).toContain('\\|'); // ebsRec.current_config contains " | "
    const dataRows = body.split('\n').filter(line => line.startsWith('| `'));
    expect(dataRows).toHaveLength(allRecs.length);
  });

  it('renders numbered recommendations with risk lines', () => {
    const body = buildPRBody(allRecs, 490.50);
    expect(body).toContain('1. **Rightsize EC2 instance');
    expect(body).toContain('2. **Purchase RDS Reserved Instance');
    expect(body).toContain('3. **Delete unused EBS volumes');
    expect(body).toContain('Risk: low');
    expect(buildPRBody([rdsRec], 280.50)).not.toContain('Risk:');
    expect(body).toContain('RDS instance has been running on-demand');
  });

  it('handles edge cases: empty recs, pipe in config values, large rec count', () => {
    const emptyBody = buildPRBody([], 0);
    expect(emptyBody).toContain('$0.00/month');
    expect(emptyBody).toContain('| Resource |');

    const recWithPipe: PRRecommendation = { ...ec2Rec, current_config: 'val1 | val2 | val3', recommended_config: 'new|config' };
    const pipeBody = buildPRBody([recWithPipe], 100);
    const tableLines = pipeBody.split('\n').filter(l => l.startsWith('| `'));
    for (const line of tableLines) {
      expect(line.startsWith('|')).toBe(true);
    }

    const recs12 = Array.from({ length: 12 }, (_, i) => ({ ...ec2Rec, resource_id: `i-${i.toString().padStart(17, '0')}`, estimated_savings: 204.17 }));
    const total = recs12.reduce((sum, r) => sum + r.estimated_savings, 0);
    const body12 = buildPRBody(recs12, total);
    expect(body12).toContain(`$${total.toFixed(2)}/month`);
    expect(body12.split('\n').filter(l => l.startsWith('| `'))).toHaveLength(12);
  });
});

// ---------------------------------------------------------------------------
// readManifest
// ---------------------------------------------------------------------------

describe('readManifest', () => {
  // readManifest validates path is inside process.cwd()/.korinfra/ — use a unique subdir there
  let testSubdir: string;
  let tmpFile: string;

  beforeEach(() => {
    testSubdir = join(process.cwd(), '.korinfra', `test-${randomUUID()}`);
    mkdirSync(testSubdir, { recursive: true });
    tmpFile = join(testSubdir, 'manifest-test.json');
  });

  afterEach(() => {
    rmSync(testSubdir, { recursive: true, force: true });
  });

  it('reads valid JSON, empty object, nested structure', async () => {
    const data = { recommendations: ['EBS-001'], scan_id: 'scan-123', version: 2 };
    await writeFile(tmpFile, JSON.stringify(data), 'utf8');
    expect(await readManifest(tmpFile)).toEqual(data);

    await writeFile(tmpFile, '{}', 'utf8');
    expect(await readManifest(tmpFile)).toEqual({});

    const nested = { meta: { region: 'us-east-1', account: '123456789012' }, stats: { total: 5, savings: 490.50 } };
    await writeFile(tmpFile, JSON.stringify(nested), 'utf8');
    const result = await readManifest(tmpFile) as typeof nested;
    expect(result.meta.region).toBe('us-east-1');
    expect(result.stats.savings).toBeCloseTo(490.50);
  });

  it('rejects for nonexistent file and invalid JSON', async () => {
    await expect(readManifest(join(testSubdir, 'nonexistent.json'))).rejects.toThrow();

    await writeFile(tmpFile, 'not-valid-json', 'utf8');
    await expect(readManifest(tmpFile)).rejects.toThrow();
  });
});
